import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      items: ['intro'],
    },
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      items: [{type: 'autogenerated', dirName: 'module1'}],
    },
    {
      type: 'category',
      label: 'Module 2: Robot Simulation (Digital Twin)',
      items: [{type: 'autogenerated', dirName: 'module2'}],
    },
    {
      type: 'category',
      label: 'Module 3: NVIDIA Isaac Platform',
      items: [{type: 'autogenerated', dirName: 'module3'}],
    },
    {
      type: 'category',
      label: 'Module 4: Humanoid Robot Development',
      items: [{type: 'autogenerated', dirName: 'module4'}],
    },
    {
      type: 'category',
      label: 'Reference',
      items: ['glossary', 'references', 'summary'],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
